---

- hosts: all
  become: true
  tasks:

  - name: update Respository and install packages on ubuntu and Rocky
    package:
      update_only: yes
      update_cache: yes
      name: 
        - "{{apache_package}}"
        - "{{php_package}}"
        - "{{htop_package}}"
      state: latest
