---

- hosts: all
  become: true
  tasks:

  - name: update Respository and install packages
    apt:
      update_cache: yes
      name: 
        - apache2
        - libapache2-mod-php
        - htop
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update respository index
    dnf:
      update_cache: yes
      name: 
        - httpd
        - php
        - htop
      state: latest
    when: ansible_distribution == "Rocky"
