---

- hosts: all
  become: true
  tasks:

  - name: update Respository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install Apache2 php htop and Packages
    apt:
      name: 
        - apache2
        - libapache2-mod-php
        - htop
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update respository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: install apache htop and packages
    dnf: 
      name: 
        - httpd
        - php
        - htop
      state: latest
    when: ansible_distribution == "Rocky"
