---

- hosts: all
  become: true
  tasks:

  - name: update Respository index
    apt:
      update_cache: yes

  - name: Remove Apache
    apt:
      name: apache2
      state: absent

  - name: Remove php
    apt:
      name: absent 
